version: '3.8'

services:
  db:
    image: postgres:15
    container_name: auth-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_service
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: auth-service
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml
    command: ["./auth-service"]

volumes:
  postgres-data: